### PR TITLE
Require Node.js 10 and remove the dependency on make-dir

### PR DESCRIPTION
**Pull request by realityking**
Less dependencies 🎉 

I also removed the dev dependency on `fs-extra` and lastly upgraded all dependencies to their newest version.

### CODE REVIEW

**Comment by pscheit** [comment]
very cool! Thank you so much

**Comment by pscheit** [comment]
I tagged it as 4.0.0 although would have maybe worked with a bump of minor version as well, but hey ;)

**Comment by realityking** [comment]
Thanks for the quick merge 😀 

I think a major is warranted with the (big) bump in Node version.

**Comment by pscheit** [comment]
exactly my thoughts. Thank you  again ;)

**Pull request merged**
